ackermann_steering_controller:
  type : ackermann_steering_controller/AckermannSteeringController

  # odom
  publish_rate : 50.0
  open_loop: false

  # joints
  rear_wheel : 'rear_wheel_joint'
  front_steer : 'front_steer_joint'

  # geometry
  # Wheel separation length between the front side and the rear side, which is used for calculating steer angle of Ackermann link mechanism.
  wheel_separation_h: 0.342
  wheel_radius: 0.0525

  # odom calibration and tuning
  wheel_seperation_h_multiplier: 1.0
  wheel_radius_multiplier: 1.0
  steer_pos_multiplier: 1.0

  # odom covariances for the encoder output of the robot
  pose_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.13 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.13 ]

  # top level frame (link) of the robot description
  base_frame_id: 'base_link'

  # transform from odom -> base_link
  enable_odom_tf: false
  odom_frame_id: 'odom_ackermann'

  # set to false if the motor driver provides velocity data:
  estimate_velocity_from_position: true

  # commands
  publish_cmd: true
  allow_multiple_cmd_vel_publishers: false

  # velocity and accel limits for the robot
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 2.0 # m/s
      has_acceleration_limits: true
      max_acceleration: 1.0 # m/s^2
  angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5 # rad/s
        has_acceleration_limits: true
        max_acceleration: 5.5 # rad/s^2

  # other
  # velocity_rolling_window_size: 10
  # cmd_vel_timeout: 0.5

