axis_linear: 3 # Right thumb stick vertical
scale_linear: 0.4
scale_linear_turbo: 2.0  # this is the commanded m/s velocity
axis_angular: 0 # Left thumb stick horizontal
scale_angular: 0.6  # this seems to act like a limit
scale_angular_turbo: 1.5
enable_button: 4
enable_turbo_button: 5