axis_linear: 1 # Left thumb stick vertical
scale_linear: 3.0
scale_linear_turbo: 6.0  # this is the commanded m/s velocity
axis_angular: 3 # Right thumb stick horizontal
scale_angular: 0.6  # this seems to act like a limit
scale_angular_turbo: 1.5
enable_button: 4
enable_turbo_button: 6