//
// Created by user on 12/23/21.
//

#ifndef ADAFRUIT_SERVO_HAT_NODE_ADAFRUIT_SERVO_HAT_NODE_H
#define ADAFRUIT_SERVO_HAT_NODE_ADAFRUIT_SERVO_HAT_NODE_H

#include "devices/pca9685.h"

#endif //ADAFRUIT_SERVO_HAT_NODE_ADAFRUIT_SERVO_HAT_NODE_H
