<!--COMPUTER ENCLOSURE-->
<link name="main_computer_enclosure">
    <inertial>
        <mass value="${scte_total_mass * 0.02}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
                ixx="1" ixy="0" ixz="0"
                iyy="1" iyz="0"
                izz="1"
        />
    </inertial>
    <visual name='visual'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.26 0.185 0.06"/>
        </geometry>
        <material name="none">
            <color rgba="${122/255} ${125/255} ${121/255} 0.5"/>
        </material>
    </visual>
    <collision name='collision'>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.26 0.185 0.06"/>
        </geometry>
    </collision>
</link>
<joint name="main_computer_enclosure_JOINED_driver_side_mounting_bar" type="fixed">
<origin xyz="0 ${(scte_chassis_width * -0.5) + (mounting_bars_width * 0.5)} ${0.06 * 0.5}" rpy="0 0 0"/>
<parent link="driver_side_mounting_bar"/>
<child link="main_computer_enclosure"/>
</joint>
        <!--/COMPUTER ENCLOSURE-->