<?xml version='1.0'?>
<!--
https://answers.ros.org/question/192817/error-msg-the-root-link_base-has-an-inertia-specified-in-the-urdf-but-kdl/
http://gazebosim.org/tutorials?tut=ros_urdf
https://wiki.ros.org/action/fullsearch/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch?action=fullsearch&context=180&value=linkto%3A%22urdf%2FTutorials%2FBuilding+a+Visual+Robot+Model+with+URDF+from+Scratch%22
http://wiki.ros.org/xacro

http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch
http://wiki.ros.org/urdf/Tutorials/Building%20a%20Movable%20Robot%20Model%20with%20URDF

http://wiki.ros.org/urdf/XML/joint#Elements

-->
<!--Gazebo does not seem to like capital letters in the robot namespace-->
<robot name="sctebot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/DEFAULTNAMESPACE2"/>
    <xacro:arg name="tf_freq" default="100.0"/>
    <xacro:arg name="pub_tf" default="false"/>

    <xacro:property name="M_PI" value="3.14159265358979323846264338327950288"/>

    <xacro:include filename="$(find scte_description)/urdf/scte.gazebo" />
    <xacro:include filename="$(find scte_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find scte_description)/urdf/macros.xacro" />

    <xacro:property name="scte_chassis_mass" value="2.9"/>
    <xacro:property name="scte_chassis_length" value="0.292"/>
    <xacro:property name="scte_chassis_width" value="0.165"/>
    <xacro:property name="scte_chassis_depth" value="0.00635"/>
    <xacro:property name="scte_chassis_length_sq" value="${scte_chassis_length * scte_chassis_length}"/>
    <xacro:property name="scte_chassis_width_sq" value="${scte_chassis_width * scte_chassis_width}"/>
    <xacro:property name="scte_chassis_depth_sq" value="${scte_chassis_depth * scte_chassis_depth}"/>

    <!--Wheel Properties-->
    <xacro:property name="wheel_mass" value="0.5"/>
    <xacro:property name="wheel_radius" value="0.0525"/>
    <xacro:property name="wheel_length" value="0.045"/>

    <xacro:property name="shock_tower_height" value="0.105"/>
    <xacro:property name="shock_tower_width" value="0.14"/>

    <xacro:property name="drive_axle_length" value="0.25"/>
    <xacro:property name="drive_axle_radius" value="0.005"/>

    <link name='base_footprint'/>

    <joint name="base_link_TO_base_footprint" type="fixed">
        <origin xyz="0 0 ${scte_chassis_depth - wheel_radius}" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link"/>
    </joint>

    <link name='base_link'>
        <visual name='visual'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${scte_chassis_length} ${scte_chassis_width} ${scte_chassis_depth}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision name='collision'>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${scte_chassis_length} ${scte_chassis_width} ${scte_chassis_depth}"/>
            </geometry>
        </collision>
    </link>

    <!-- Inertial link stores the robot's inertial information -->
    <link name="inertial_link">
        <inertial>
            <mass value="${scte_chassis_mass}" />
            <origin xyz="0 0 0" />
            <inertia ixx="${(1/12 * scte_chassis_mass) * (scte_chassis_depth_sq + scte_chassis_width_sq)}" ixy="0" ixz="0"
                     iyy="${(1/12 * scte_chassis_mass) * (scte_chassis_depth_sq + scte_chassis_length_sq)}" iyz="0"
                     izz="${(1/12 * scte_chassis_mass) * (scte_chassis_length_sq + scte_chassis_width_sq)}" />
        </inertial>
    </link>

    <joint name="inertial_to_base_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!--CHASSIS-->
    <link name="scte_chassis"/>

    <joint name="scte_chassis_to_base_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="scte_chassis"/>
    </joint>

    <!---->
    <xacro:include filename="$(find scte_description)/urdf/scte_diff_and_shock_tower.xacro"/>
    <xacro:scte_diff_and_shock_tower link_name="front_diff_tower"
                                parent_link="scte_chassis"
                                diff_joint_xyz="${scte_chassis_length * 0.63} 0 0"
                                diff_joint_rpy="0 0 0"
                                diff_plate_size="0.07 0.07 ${scte_chassis_depth}"

                                shock_tower_size="0.015 ${shock_tower_width} ${shock_tower_height}"
                                shock_tower_joint_origin="0 0 ${shock_tower_height * 0.5}"
                                shock_tower_joint_rpy="0 0 0"
    />
    <xacro:scte_diff_and_shock_tower link_name="rear_diff_tower"
                                     parent_link="scte_chassis"
                                     diff_joint_xyz="${scte_chassis_length * -0.63} 0 0"
                                     diff_joint_rpy="0 0 0"
                                     diff_plate_size="0.07 0.07 ${scte_chassis_depth}"

                                     shock_tower_size="0.015 ${shock_tower_width} ${shock_tower_height}"
                                     shock_tower_joint_origin="0 0 ${shock_tower_height * 0.5}"
                                     shock_tower_joint_rpy="0 0 0"
    />

    <xacro:include filename="$(find scte_description)/urdf/scte_front_bumper.xacro"/>
    <xacro:scte_front_bumper link_name="front_bumper"
                             parent_link="front_diff_tower"
                             front_skid_plate_size="0.07 0.07 ${scte_chassis_depth}"
                             front_skid_plate_joint_xyz="${0.07} 0 ${0.07 * 0.30}"
                             front_skid_plate_joint_rpy="0 ${M_PI/-6}  0"
                             front_bumper_size="0.01 0.175 0.05"
    />

    <xacro:include filename="$(find scte_description)/urdf/scte_rear_bumper.xacro"/>
    <xacro:scte_rear_bumper link_name="rear_bumper"
                            parent_link="rear_diff_tower"
                            rear_bumper_size="0.01 0.255 0.05"
                            rear_bumper_mount_size="0.09 0.05 0.05"
                            rear_bumper_mount_joint_xyz="${0.09 * -0.6} 0 ${shock_tower_height * 0.5}"
                            rear_bumper_mount_joint_rpy="0 0 0"
    />

    <xacro:include filename="$(find scte_description)/urdf/scte_drive_axle.xacro"/>
    <xacro:scte_drive_axle link_name="front_axle"
                     parent_link="front_diff_tower"
                     drive_axle_radius="${drive_axle_radius}"
                     drive_axle_length="${drive_axle_length}"
                     drive_axle_joint_xyz="0 0 ${0.03 * 0.5}"
                     drive_axle_joint_rpy="${M_PI * -0.5} 0 0"
    />
    <xacro:include filename="$(find scte_description)/urdf/scte_drive_axle.xacro"/>
    <xacro:scte_drive_axle link_name="rear_axle"
                           parent_link="rear_diff_tower"
                           drive_axle_radius="${drive_axle_radius}"
                           drive_axle_length="${drive_axle_length}"
                           drive_axle_joint_xyz="0 0 ${0.03 * 0.5}"
                           drive_axle_joint_rpy="${M_PI * -0.5} 0 0"
    />

    <xacro:include filename="$(find scte_description)/urdf/scte_wheel.xacro"/>
    <xacro:scte_wheel link_name="front_left_wheel"
                      parent_link="front_axle"
                      wheel_radius="${wheel_radius}"
                      wheel_length="${wheel_length}"
                      wheel_joint_origin="0 0 ${drive_axle_length * 0.5}"
                      wheel_joint_rpy="${M_PI * -0.5} 0 0"
                      wheel_joint_name="front_left_wheel_TO_front_axle"
                      wheel_steer_joint_name="front_left_wheel_steer_TO_front_axle"
                      is_steerable="true"
    />
    <xacro:scte_wheel link_name="front_right_wheel"
                      parent_link="front_axle"
                      wheel_radius="${wheel_radius}"
                      wheel_length="${wheel_length}"
                      wheel_joint_origin="0 0 ${drive_axle_length * -0.5}"
                      wheel_joint_rpy="${M_PI * -0.5} 0 0"
                      wheel_joint_name="front_right_wheel_TO_front_axle"
                      wheel_steer_joint_name="front_right_wheel_steer_TO_front_axle"
                      is_steerable="true"
    />
    <xacro:scte_wheel link_name="rear_left_wheel"
                      parent_link="rear_axle"
                      wheel_radius="${wheel_radius}"
                      wheel_length="${wheel_length}"
                      wheel_joint_origin="0 0 ${drive_axle_length * 0.5}"
                      wheel_joint_rpy="${M_PI * -0.5} 0 0"
                      wheel_joint_name="rear_left_wheel_TO_rear_axle"
                      wheel_steer_joint_name="rear_left_wheel_steer_TO_rear_axle"
                      is_steerable="false"
    />

    <xacro:scte_wheel link_name="rear_right_wheel"
                      parent_link="rear_axle"
                      wheel_radius="${wheel_radius}"
                      wheel_length="${wheel_length}"
                      wheel_joint_origin="0 0 ${drive_axle_length * -0.5}"
                      wheel_joint_rpy="${M_PI * -0.5} 0 0"
                      wheel_joint_name="rear_right_wheel_TO_rear_axle"
                      wheel_steer_joint_name="rear_right_wheel_steer_TO_rear_axle"
                      is_steerable="false"
    />
    -->

</robot>