# REF DOCS:
# http://docs.ros.org/en/melodic/api/robot_localization/html/configuring_robot_localization.html
# http://docs.ros.org/en/noetic/api/robot_localization/html/
# https://github.com/methylDragon/ros-sensor-fusion-tutorial/blob/master/01%20-%20ROS%20and%20Sensor%20Fusion%20Tutorial.md
# https://github.com/locusrobotics/fuse/issues/179
# https://github.com/cra-ros-pkg/robot_localization

ekf_se_odom:
  frequency: 50
  sensor_timeout: 0.1
  two_d_mode: false

  transform_time_offset: 0.1
  transform_timeout: 0.0

  predict_to_current_time: true

  print_diagnostics: true
  debug: false
  debug_out_file: /path/to/debug/file.txt

  publish_tf: true
  publish_acceleration: false

  map_frame: map              # Defaults to "map" if unspecified
  odom_frame: odom           # Defaults to "odom" if unspecified
  base_link_frame: base_footprint  # Defaults to "base_link" if unspecified
  world_frame: odom           # Defaults to the value of odom_frame if unspecified

  # x, y , z
  # r, p, y
  # vx, vy, vz
  # vr, vp, vy
  # ax, ay, az

  odom0: ackermann_steering_controller/odom
  odom0_config: [false,  false,  false,
                 false, false, false,
                 true, true, false,
                 false, false, true,
                 false, false, false]
  odom0_differential: false
  odom0_relative: false
  odom0_queue_size: 10
  odom0_pose_rejection_threshold: 15 # 2
  odom0_twist_rejection_threshold: 3 # 0.2
  odom0_nodelay: false

  odom1: rtabmap/odom
  odom1_config: [ false,  false,  false,
                  false, false, false,
                  true, true, false,
                  false, false, false,
                  false, false, false ]
  odom1_differential: false
  odom1_relative: false
  odom1_queue_size: 10
  odom1_pose_rejection_threshold: 15 # 2
  odom1_twist_rejection_threshold: 3 # 0.2
  odom1_nodelay: false

  imu0: adafruit_10dof_imu/imu/data
  imu0_config: [true, true, true,
                true, true, true,
                false, false, false,
                false, false, false,
                false, false, false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
  imu0_twist_rejection_threshold: 0.8                #
  imu0_linear_acceleration_rejection_threshold: 0.8  #
  imu0_remove_gravitational_acceleration: false

  imu1: realsense_d435i/imu_corrected/data
  imu1_config: [true, true, true,
                true, true, true,
                false, false, false,
                false, false, false,
                false, false, false]
  imu1_nodelay: false
  imu1_differential: false
  imu1_relative: false
  imu1_queue_size: 10
  imu1_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
  imu1_twist_rejection_threshold: 0.8                #
  imu1_linear_acceleration_rejection_threshold: 0.8  #
  imu1_remove_gravitational_acceleration: false

  imu2: gazebo/imu
  imu2_config: [ false, false, false,
                 false, false, true,
                 false, false, false,
                 false, false, true,
                 true, true, false ]
  imu2_nodelay: false
  imu2_differential: false
  imu2_relative: false
  imu2_queue_size: 10
  imu2_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
  imu2_twist_rejection_threshold: 0.8                #
  imu2_linear_acceleration_rejection_threshold: 0.8  #
  imu2_remove_gravitational_acceleration: false

  # [ADVANCED] Some IMUs automatically remove acceleration due to gravity, and others don't. If yours doesn't, please set
  # this to true, and *make sure* your data conforms to REP-103, specifically, that the data is in ENU frame.
  #imu0_remove_gravitational_acceleration: true

  use_control: false # was true
  stamped_control: false
  control_timeout: 0.2
  control_config: [true, false, false, false, false, true]

  acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
  deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
  acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
  deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

  process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                             0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]

  initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]

ekf_se_map:
  frequency: 50
  sensor_timeout: 0.1
  two_d_mode: false

  transform_time_offset: 0.1
  transform_timeout: 0.0
  predict_to_current_time: true

  print_diagnostics: true
  debug: false
  debug_out_file: /path/to/debug/file.txt

  publish_tf: true
  publish_acceleration: false

  map_frame: map
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: map

  # x, y , z
  # r, p, y
  # vx, vy, vz
  # vr, vp, vy
  # ax, ay, az

  # ODOMs
  odom0: ackermann_steering_controller/odom
  odom0_config: [ false,  false,  false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false ]
  odom0_differential: false
  odom0_relative: false
  odom0_queue_size: 10
  odom0_pose_rejection_threshold: 15 # 2
  odom0_twist_rejection_threshold: 2 # 0.2
  odom0_nodelay: false

  odom1: adafruit_ultimate_gps/odometry/gps
  odom1_config: [ true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false ]
  odom1_queue_size: 10
  odom1_nodelay: true
  odom1_differential: false
  odom1_relative: false

  odom2: gazebo/odometry/gps
  odom2_config: [ true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false ]
  odom2_queue_size: 10
  odom2_nodelay: true
  odom2_differential: false
  odom2_relative: false

  # IMUs
  imu0: adafruit_10dof_imu/imu/data
  imu0_config: [ false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, true,
                 true, true, false ]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: false
  imu0_queue_size: 10
  imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
  imu0_twist_rejection_threshold: 0.8                #
  imu0_linear_acceleration_rejection_threshold: 0.8  #
  imu0_remove_gravitational_acceleration: false

  imu1: realsense_d435i/imu_corrected/data
  imu1_config: [ false, false, false,
                 false, false, false,
                 false, false, false,
                 false, false, true,
                 true, true, false ]
  imu1_nodelay: false
  imu1_differential: false
  imu1_relative: false
  imu1_queue_size: 10
  imu1_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
  imu1_twist_rejection_threshold: 0.8                #
  imu1_linear_acceleration_rejection_threshold: 0.8  #
  imu1_remove_gravitational_acceleration: false

  imu2: gazebo/imu
  imu2_config: [ false, false, false,
                 false, false, true,
                 false, false, false,
                 false, false, true,
                 true, true, false ]
  imu2_nodelay: false
  imu2_differential: false
  imu2_relative: false
  imu2_queue_size: 10
  imu2_remove_gravitational_acceleration: false

  use_control: false

  process_noise_covariance: [ 1.0,  0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    1.0,  0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    1e-3, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0.3,  0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0.3,  0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0.01, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0.5,   0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0.5,   0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0.1,  0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0.3,  0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.3,  0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.3,  0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.3,  0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.3,  0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.3 ]

  initial_estimate_covariance: [ 1.0,  0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    1.0,  0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    1.0,  0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    1.0,  0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    1.0,  0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    1.0,  0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    1.0,  0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    1.0,   0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1.0,   0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1.0,   0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1.0,  0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1.0,  0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1.0 ]

gazebo_navsat_transform:
  frequency: 30
  delay: 3.0
  magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
  yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
  zero_altitude: false
  broadcast_cartesian_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false

ultimate_gps_navsat_transform:
  frequency: 30
  delay: 3.0
  magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
  yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
  zero_altitude: false
  broadcast_cartesian_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false

gpsd_navsat_transform:
  frequency: 30
  delay: 3.0
  magnetic_declination_radians: 0.0429351  # For lat/long 55.944831, -3.186998
  yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
  zero_altitude: false
  broadcast_cartesian_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false
