sctebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_rear_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_rear_JOINED_axle_rear
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_rear_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_rear_JOINED_axle_rear
    pid: {p: 100.0, i: 0.01, d: 10.0}