ackermann_steering_bot_controller:
  type : ackermann_steering_controller/AckermannSteeringController
  rear_wheel : 'rear_wheel_joint'
  front_steer : 'front_steer_joint'
  publish_rate : 50.0

  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  cmd_vel_timeout: 20.0

  #wheel_seperation_h : 0.4
  #wheel_radius : 0.11
  wheel_seperation_h_multiplier: 0.257 # calibration parameter for odometory, needed for test.

  #wheel_radius_multiplier       : 1.0 # calibration parameter for linear odometory
  #steer_pos_multiplier          : 1.0
  #base_frame_id                 : base_link

  #enable_odom_tf: true

  #linear:
  #  x:
  #    has_velocity_limits       : true
  #    max_velocity              : 0.9  # m/s
  #    min_velocity              : -0.9 # m/s
  #    has_acceleration_limits   : true
  #    max_acceleration          : 1.7  # m/s^2
  #    min_acceleration          : -0.4 # m/s^2
  #    has_jerk_limits           : true
  #    max_jerk                  : 5.0 # m/s^3
  #angular:
  #  z:
  #    has_velocity_limits       : true
  #    max_velocity              : 0.5  # rad/s
#    has_acceleration_limits   : true
#    max_acceleration          : 1.5  # rad/s^2
#    has_jerk_limits           : true
#    max_jerk                  : 2.5 # rad/s^3