axis_linear: 1 # Left thumb stick vertical
scale_linear: 0.4
scale_linear_turbo: 1.0
axis_angular: 2 # Right thumb stick horizontal
scale_angular: 0.6
scale_angular_turbo: 1.0
enable_button: 4
enable_turbo_button: 5