# this is a bare bones control config to test the joints that is modeled
# after the ros_control tutorial: http://gazebosim.org/tutorials?tut=ros_control&cat=connect_ros

# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Wheel Position Controllers:
front_left_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_right_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

rear_left_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

rear_right_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Wheel Steer Controllers
front_left_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_left_steer_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

front_right_steer_position_controller:
  type: effort_controllers/JointPositionController
  joint: front_right_steer_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Simple Rear Wheel Joint
rear_wheel_position_controller:
  type: effort_controllers/JointPositionController
  joint: rear_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}